language: php

php:
    - '7.4'

cache:
    directories:
        - vendor

before_script:
    - composer self-update && composer --version
    - composer install --dev

script:
    - composer lint
    - phpunit
