language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
    
cache:
    directories:
        - vendor

install:
    - composer self-update && composer --version
    - composer install --dev

before_script:
    - phpenv config-rm xdebug.ini

script: 
    - phpunit
    