language: php

php:
    - '7.2'
    - '7.4'
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

cache:
    directories:
        - vendor

before_script:
    - composer self-update && composer --version
    - composer install --dev

script:
    - composer lint
    - phpunit
