language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
    
env:
    - TESTBENCH_VERSION="3.0.*"
    - TESTBENCH_VERSION="3.1.*"
    - TESTBENCH_VERSION="3.2.*"
    - TESTBENCH_VERSION="3.3.*"
    
cache:
    directories:
        - vendor
        
before_script:
    - composer self-update && composer --version

install:
    - composer require-dev orchestra/testbench=${TESTBENCH_VERSION}
    - composer install --dev

script: 
    - phpunit