language: php

php:
    - '5.6'
    - '7.0'
    - hhvm

matrix:
    allow_failures:
    - php: hhvm

cache:
    directories:
        - vendor

before_script:
    - composer self-update && composer --version
    - composer install --dev

script:
    - phpunit
